common: &common
  adapter: postgresql
  username: rails
  password: easy_pass
  host: localhost

development:
  <<: *common
  database: league_dev
  host: localhost

test:
  <<: *common
  database: league_test

production:
  <<: *common
  database: league_prod
